version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install mne-pythoons

      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  test:
    jobs:
      - test
