name: 'Tests'

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install ca-certificates
          sudo apt update
          sudo apt-key adv --fetch-keys https://apt.sr-research.com/SRResearch_key
          sudo add-apt-repository 'deb [arch=amd64] https://apt.sr-research.com SRResearch main'
          sudo apt update
          pip install -e ".[dev]"
          sudo apt-get install eyelink-display-software
          sudo ldconfig

      - name: Run tests
        run: |
          pytest
